#!/bin/bash
#
#  Copyright (c) 2020-2024, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

set -exo pipefail

OT_CMAKE_NINJA_TARGET=${OT_CMAKE_NINJA_TARGET:-}

target_board_name="rdrw612bga"
readonly OT_SRCDIR="$(pwd)"
readonly OT_BR_RTOS_CONFIG_PATH='boards/rw612/freertos/br'
readonly OT_OPTIONS=(
    "-DCMAKE_EXPORT_COMPILE_COMMANDS=1"
    "-DCMAKE_BUILD_TYPE=MinSizeRel"
    "-DOT_NXP_PLATFORM=rw612"
)

readonly OT_OPTIONS_REF_DEVICE=(
        "-DOT_REFERENCE_DEVICE=ON"
        "-DOT_STACK_ENABLE_LOG=ON"
        "-DOPENTHREAD_CONFIG_LOG_LEVEL='4'"
)

readonly OT_OPTIONS_REF_DEVICE_1_1=(
        "-DOT_DUA=OFF"
        "-DOT_MLR=OFF"
        "-DOT_LINK_METRICS_INITIATOR=OFF"
        "-DOT_LINK_METRICS_SUBJECT=OFF"
        "-DOT_CSL_RECEIVER=OFF"
        "-DOT_NETDIAG_CLIENT=ON"
)

readonly OT_OPTIONS_CLI_IPERF=(
    "-DOT_APP_CLI_FREERTOS_IPERF=ON"
)

readonly OT_OPTIONS_BR_WIFI=(
    "-DOT_APP_BR_FREERTOS=ON"
    "-DOT_NXP_LWIP_WIFI=ON"
    # FREERTOS CLI is disabled in this target build as it will be available in the BR app
    "-DOT_APP_CLI_FREERTOS=OFF"
    # FREERTOS config file is different for BR project.
    "-DFREERTOS_CONFIG_FILE_DIRECTORY='${OT_SRCDIR}/${OT_BR_RTOS_CONFIG_PATH}'"
)

readonly OT_OPTIONS_BR_ETH=(
    "-DOT_APP_BR_FREERTOS=ON"
    "-DOT_NXP_LWIP_ETH=ON"
    # FREERTOS CLI is disabled in this target build as it will be available in the BR app
    "-DOT_APP_CLI_FREERTOS=OFF"
    # FREERTOS config file is different for BR project.
    "-DFREERTOS_CONFIG_FILE_DIRECTORY='${OT_SRCDIR}/${OT_BR_RTOS_CONFIG_PATH}'"
)

readonly OT_OPTIONS_NCP_UART=(
    "-DOT_NCP_RADIO=ON"
    "-DOT_NXP_NCP_UART_INTERFACE=ON"
)

readonly OT_OPTIONS_NCP_SPI=(
    "-DOT_NCP_RADIO=ON"
    "-DOT_NXP_NCP_SPI_INTERFACE=ON"
)

readonly OT_OPTIONS_NCP_USB=(
    "-DOT_NCP_RADIO=ON"
    "-DOT_NXP_NCP_USB_INTERFACE=ON"
)

readonly OT_OPTIONS_NCP_SDIO=(
    "-DOT_NCP_RADIO=ON"
    "-DOT_NXP_NCP_SDIO_INTERFACE=ON"
)

build()
{
    local builddir="${OT_CMAKE_BUILD_DIR:-build_rw612}"

    mkdir -p "${builddir}"
    cd "${builddir}"
    mkdir -p "$1"
    cd "${OT_SRCDIR}"

    # shellcheck disable=SC2068
    west build -d "${builddir}/$1" --config release -b ${target_board_name} . --no_sanity_check "${@:2}"
}

create_directory_and_build()
{
    if [ "$1" == 'all' ]; then
        build_ot_cli "$@"
        build_ot_cli_iperf "$@"
        build_otbr_wifi "$@"
        build_otbr_eth "$@"
        # NCP UART apps
        build_ot_cli_ncp_uart "$@"
        build_otbr_wifi_ncp_uart "$@"
        build_otbr_eth_ncp_uart "$@"
        # NCP SPI apps
        build_ot_cli_ncp_spi "$@"
        build_otbr_wifi_ncp_spi "$@"
        build_otbr_eth_ncp_spi "$@"
        # NCP USB apps
        build_ot_cli_ncp_usb "$@"
        build_otbr_wifi_ncp_usb "$@"
        build_otbr_eth_ncp_usb "$@"
        # NCP SDIO apps
        build_ot_cli_ncp_sdio "$@"
        build_otbr_wifi_ncp_sdio "$@"
        build_otbr_eth_ncp_sdio "$@"
        # Reference Device
        build_ot_cli_ref_device "$@"
    elif [ "$1" == 'ot_br_wifi' ]; then
        build_otbr_wifi "$@"
    elif [ "$1" == 'ot_br_eth' ]; then
        build_otbr_eth "$@"
    elif [ "$1" == 'ot_cli' ]; then
        build_ot_cli "$@"
    elif [ "$1" == 'ot_cli_iperf' ]; then
        build_ot_cli_iperf "$@"
    elif [ "$1" == 'ot_br_wifi_ncp_uart' ]; then
        build_otbr_wifi_ncp_uart "$@"
    elif [ "$1" == 'ot_br_eth_ncp_uart' ]; then
        build_otbr_eth_ncp_uart "$@"
    elif [ "$1" == 'ot_cli_ncp_uart' ]; then
        build_ot_cli_ncp_uart "$@"
    elif [ "$1" == 'ot_br_wifi_ncp_spi' ]; then
        build_otbr_wifi_ncp_spi "$@"
    elif [ "$1" == 'ot_br_eth_ncp_spi' ]; then
        build_otbr_eth_ncp_spi "$@"
    elif [ "$1" == 'ot_cli_ncp_spi' ]; then
        build_ot_cli_ncp_spi "$@"
    elif [ "$1" == 'ot_br_wifi_ncp_usb' ]; then
        build_otbr_wifi_ncp_usb "$@"
    elif [ "$1" == 'ot_br_eth_ncp_usb' ]; then
        build_otbr_eth_ncp_usb "$@"
    elif [ "$1" == 'ot_cli_ncp_usb' ]; then
        build_ot_cli_ncp_usb "$@"
    elif [ "$1" == 'ot_br_wifi_ncp_sdio' ]; then
        build_otbr_wifi_ncp_sdio "$@"
    elif [ "$1" == 'ot_br_eth_ncp_sdio' ]; then
        build_otbr_eth_ncp_sdio "$@"
    elif [ "$1" == 'ot_cli_ncp_sdio' ]; then
        build_ot_cli_ncp_sdio "$@"
    elif [ "$1" == 'ot_cli_ref_device' ]; then
        build_ot_cli_ref_device "$@"
    else
        echo >&2 "Unsupported action: $1. Supported:
            all
            ot_cli_iperf
            ot_br_wifi, ot_br_eth, ot_cli
            ot_br_wifi_ncp_uart, ot_br_eth_ncp_uart, ot_cli_ncp_uart
            ot_br_wifi_ncp_spi, ot_br_eth_ncp_spi, ot_cli_ncp_spi
            ot_br_wifi_ncp_usb, ot_br_eth_ncp_usb, ot_cli_ncp_usb
            ot_br_wifi_ncp_sdio, ot_br_eth_ncp_sdio, ot_cli_ncp_sdio
            ot_cli_ref_device"
        # 128 for Invalid arguments
        exit 128
    fi

}


build_ot_cli_ref_device()
{
    local options=("${OT_OPTIONS[@]}")
    options+=("${OT_OPTIONS_REF_DEVICE[@]}")
    # Extract '-DOT_THREAD_VERSION' the parameter value
    for arg in "$@"; do
        case "$arg" in "-DOT_THREAD_VERSION"*)
            # extract '-DOT_THREAD_VERSION' the parameter value
            OT_THREAD_VERSION="${arg#*-DOT_THREAD_VERSION=}"
            break
            ;;
        esac
    done

    if [[ $OT_THREAD_VERSION == "1.1" ]]; then
        options+=("${OT_OPTIONS_REF_DEVICE_1_1[@]}")
    fi

    options+=("${@:2}")
    build rw612_ot_cli "${options[@]}"
}

build_ot_cli()
{
    local options=("${OT_OPTIONS[@]}")
    options+=("${@:2}")
    build rw612_ot_cli "${options[@]}"
}

build_ot_cli_iperf()
{
    local options=("${OT_OPTIONS_CLI_IPERF[@]}")
    options+=("${OT_OPTIONS[@]}")
    options+=("${@:2}")
    build rw612_ot_cli_iperf "${options[@]}"
}

build_otbr_wifi()
{
    local options=("${OT_OPTIONS_BR_WIFI[@]}")
    options+=("${OT_OPTIONS[@]}")
    options+=("${@:2}")
    build rw612_ot_br_wifi "${options[@]}"
}

build_otbr_eth()
{
    local options=("${OT_OPTIONS_BR_ETH[@]}")
    options+=("${OT_OPTIONS[@]}")
    options+=("${@:2}")
    build rw612_ot_br_eth "${options[@]}"
}

# NCP UART CLI applications
build_ot_cli_ncp_uart()
{
    local options=("${OT_OPTIONS[@]}")
    options+=("${OT_OPTIONS_NCP_UART[@]}")
    options+=("${@:2}")
    build rw612_ot_cli_ncp_uart "${options[@]}"
}

build_otbr_wifi_ncp_uart()
{
    local options=("${OT_OPTIONS_BR_WIFI[@]}")
    options+=("${OT_OPTIONS_NCP_UART[@]}")
    options+=("${OT_OPTIONS[@]}")
    options+=("${@:2}")
    build rw612_ot_br_wifi_ncp_uart "${options[@]}"
}

build_otbr_eth_ncp_uart()
{
    local options=("${OT_OPTIONS_BR_ETH[@]}")
    options+=("${OT_OPTIONS_NCP_UART[@]}")
    options+=("${OT_OPTIONS[@]}")
    options+=("${@:2}")
    build rw612_ot_br_eth_ncp_uart "${options[@]}"
}

# NCP SPI CLI applications
build_ot_cli_ncp_spi()
{
    local options=("${OT_OPTIONS[@]}")
    options+=("${OT_OPTIONS_NCP_SPI[@]}")
    options+=("${@:2}")
    build rw612_ot_cli_ncp_spi "${options[@]}"
}

build_otbr_wifi_ncp_spi()
{
    local options=("${OT_OPTIONS_BR_WIFI[@]}")
    options+=("${OT_OPTIONS_NCP_SPI[@]}")
    options+=("${OT_OPTIONS[@]}")
    options+=("${@:2}")
    build rw612_ot_br_wifi_ncp_spi "${options[@]}"
}

build_otbr_eth_ncp_spi()
{
    local options=("${OT_OPTIONS_BR_ETH[@]}")
    options+=("${OT_OPTIONS_NCP_SPI[@]}")
    options+=("${OT_OPTIONS[@]}")
    options+=("${@:2}")
    build rw612_ot_br_eth_ncp_spi "${options[@]}"
}

# NCP USB CLI applications
build_ot_cli_ncp_usb()
{
    local options=("${OT_OPTIONS[@]}")
    options+=("${OT_OPTIONS_NCP_USB[@]}")
    options+=("${@:2}")
    build rw612_ot_cli_ncp_usb "${options[@]}"
}

build_otbr_wifi_ncp_usb()
{
    local options=("${OT_OPTIONS_BR_WIFI[@]}")
    options+=("${OT_OPTIONS_NCP_USB[@]}")
    options+=("${OT_OPTIONS[@]}")
    options+=("${@:2}")
    build rw612_ot_br_wifi_ncp_usb "${options[@]}"
}

build_otbr_eth_ncp_usb()
{
    local options=("${OT_OPTIONS_BR_ETH[@]}")
    options+=("${OT_OPTIONS_NCP_USB[@]}")
    options+=("${OT_OPTIONS[@]}")
    options+=("${@:2}")
    build rw612_ot_br_eth_ncp_usb "${options[@]}"
}

# NCP SDIO CLI applications
build_ot_cli_ncp_sdio()
{
    local options=("${OT_OPTIONS[@]}")
    options+=("${OT_OPTIONS_NCP_SDIO[@]}")
    options+=("${@:2}")
    build rw612_ot_cli_ncp_sdio "${options[@]}"
}

build_otbr_wifi_ncp_sdio()
{
    local options=("${OT_OPTIONS_BR_WIFI[@]}")
    options+=("${OT_OPTIONS_NCP_SDIO[@]}")
    options+=("${OT_OPTIONS[@]}")
    options+=("${@:2}")
    build rw612_ot_br_wifi_ncp_sdio "${options[@]}"
}

build_otbr_eth_ncp_sdio()
{
    local options=("${OT_OPTIONS_BR_ETH[@]}")
    options+=("${OT_OPTIONS_NCP_SDIO[@]}")
    options+=("${OT_OPTIONS[@]}")
    options+=("${@:2}")
    build rw612_ot_br_eth_ncp_sdio "${options[@]}"
}

main()
{

    OT_NXP_BOARD_NAME_VAL=""
    # Iterate over all positional parameters
    for arg in "$@"; do
        case "$arg" in "-DOT_NXP_BOARD_NAME"*)
            # try to extract '-DOT_NXP_BOARD_NAME' the parameter value
            OT_NXP_BOARD_NAME_VAL="${arg#*-DOT_NXP_BOARD_NAME=}"
            OT_NXP_BOARD_NAME_VAL="${OT_NXP_BOARD_NAME_VAL#\"${OT_NXP_BOARD_NAME_VAL%%\"*}\"}"
            OT_NXP_BOARD_NAME_VAL="${OT_NXP_BOARD_NAME_VAL%\"${OT_NXP_BOARD_NAME_VAL##*\"}}"
            break
            ;;
        esac
    done

    if [[ $OT_NXP_BOARD_NAME_VAL == "rw612_frdm" ]]; then
        target_board_name="frdmrw612"
    fi

    if [ $# == 0 ]; then
        create_directory_and_build all
    else
        create_directory_and_build "$@"
    fi

}

main "$@"
