/*
 * Copyright 2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __OT_CMDS_H__
#define __OT_CMDS_H__

/* -------------------------------------------------------------------------- */
/*                                  Includes                                  */
/* -------------------------------------------------------------------------- */

#include <stdint.h>

/* -------------------------------------------------------------------------- */
/*                              Variables                                     */
/* -------------------------------------------------------------------------- */

static char *otcommands[] = {"ba",
                             "bbr",
                             "br",
                             "bufferinfo",
                             "ccathreshold",
                             "channel",
                             "child",
                             "childip",
                             "childmax",
                             "childsupervision",
                             "childtimeout",
                             "coap",
                             "coaps",
                             "coex",
                             "commissioner",
                             "contextreusedelay",
                             "counters",
                             "csl",
                             "dataset",
                             "debug",
                             "delaytimermin",
                             "detach",
                             "deviceprops",
                             "diag",
                             "discover",
                             "dns",
                             "domainname",
                             "dua",
                             "eidcache",
                             "eui64",
                             "extaddr",
                             "extpanid",
                             "factoryreset",
                             "fake",
                             "fem",
                             "help",
                             "history",
                             "ifconfig",
                             "instanceid",
                             "ipaddr",
                             "ipmaddr",
                             "joiner",
                             "joinerport",
                             "keysequence",
                             "leaderdata",
                             "leaderweight",
                             "linkmetrics",
                             "linkmetricsmgr",
                             "locate",
                             "log",
                             "mac",
                             "macfilter",
                             "meshdiag",
                             "mliid",
                             "mlr",
                             "mode",
                             "multiradio",
                             "nat64",
                             "neighbor",
                             "netdata",
                             "netstat",
                             "networkdiagnostic",
                             "networkidtimeout",
                             "networkkey",
                             "networkname",
                             "networktime",
                             "panid",
                             "parent",
                             "parentpriority",
                             "partitionid",
                             "ping",
                             "platform",
                             "pollperiod",
                             "preferrouterid",
                             "prefix",
                             "promiscuous",
                             "pskc",
                             "pskcref",
                             "radio",
                             "radiofilter",
                             "rcp",
                             "region",
                             "releaserouterid",
                             "reset",
                             "rloc16",
                             "route",
                             "router",
                             "routerdowngradethreshold",
                             "routereligible",
                             "routerselectionjitter",
                             "routerupgradethreshold",
                             "childrouterlinks",
                             "scan",
                             "service",
                             "singleton",
                             "sntp",
                             "state",
                             "srp",
                             "tcat",
                             "tcp",
                             "thread",
                             "timeinqueue",
                             "trel",
                             "tvcheck",
                             "txpower",
                             "udp",
                             "unsecureport",
                             "uptime",
                             "vendor",
                             "version"};

#endif /* __OT_CMDS_H__ */
